/* Runs the bundled dist/Code_Ledger.gs against an in-memory Sheet (same emulation as the ctl test). */
const fs = require("fs"), vm = require("vm"), path = require("path"), crypto = require("crypto"), root = path.join(__dirname, "../..");
function start(extraProps, extraSource, shared, codePath) {
const sheets = (shared && shared.sheets) || {}, cache = {}, props = Object.assign({ SOB_INITIAL_ADMIN_PIN: "Adm1n-Setup-77" }, extraProps || {});
/* Google Sheets turns text that LOOKS like a date, a date-time or a number into a real date / number when a script writes it (setValues), and getValues then returns Date objects. Emulated so tests see what the real Sheet does. */
const sheetsParse = (x) => { if (typeof x !== "string") return x; let m;
  if ((m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(x))) { const t = Date.UTC(+m[1], +m[2] - 1, +m[3]); const d = new Date(t); return d.getUTCMonth() === +m[2] - 1 ? new Date(t - 3 * 3600 * 1000) : x; }   // midnight in East Africa Time
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/.test(x)) return new Date(x);
  if (/^-?\d+(\.\d+)?$/.test(x) && x.length < 16) return Number(x);
  return x; };
const mk = () => { const d = [], fmt = {}; let maxRows = 1000; return { getLastRow: () => d.length, getMaxRows: () => maxRows, insertRowsAfter: (after, n) => { maxRows += n; }, clear: () => { d.length = 0; }, getLastColumn: () => d.reduce((a, r) => Math.max(a, r.length), 0), getRange(r, c, nr, nc) { if (r - 1 + nr > maxRows) throw new Error("The coordinates or dimensions of the range are invalid."); return { getNumberFormat: () => fmt[c] || "General", setNumberFormat: (f) => { for (let j = 0; j < nc; j++) fmt[c + j] = f; }, getValues: () => Array.from({ length: nr }, (_, i) => Array.from({ length: nc }, (_, j) => (d[r - 1 + i] && d[r - 1 + i][c - 1 + j] !== undefined ? d[r - 1 + i][c - 1 + j] : ""))), setValues: (v) => { if (v.length !== nr || v.some((row) => row.length !== nc)) throw new Error("The number of columns in the data does not match the number of columns in the range. The data has " + (v[0] ? v[0].length : 0) + " but the range has " + nc + "."); v.forEach((row, i) => row.forEach((x, j) => { d[r - 1 + i] = d[r - 1 + i] || []; d[r - 1 + i][c - 1 + j] = fmt[c + j] === "@" ? (x === "" || x === null || x === undefined ? x : String(x)) : sheetsParse(x); })); }, clearContent: () => { for (let i = 0; i < nr; i++) if (d[r - 1 + i]) for (let j = 0; j < nc; j++) d[r - 1 + i][c - 1 + j] = ""; } }; } }; };
const sb = { SpreadsheetApp: { getActiveSpreadsheet: () => ({ getSpreadsheetTimeZone: () => "Africa/Kampala", getSheetByName: (n) => sheets[n] || null, insertSheet: (n) => (sheets[n] = mk()) }) }, LockService: { getScriptLock: () => ({ waitLock() {}, releaseLock() {} }) },
  UrlFetchApp: { fetch() { throw new Error("no network in tests"); } },
    CacheService: { getScriptCache: () => ({ get: (k) => cache[k] || null, put: (k, v) => { cache[k] = v; }, remove: (k) => { delete cache[k]; } }) },
  Utilities: { formatDate: (d, tz, f) => { const p = Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone: tz, hourCycle: "h23", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit" }).formatToParts(d).map((x) => [x.type, x.value])); return f.replace("yyyy", p.year).replace("MM", p.month).replace("dd", p.day).replace("HH", p.hour).replace("mm", p.minute).replace("ss", p.second); }, DigestAlgorithm: { SHA_256: 1 }, Charset: { UTF_8: 1 }, computeDigest: (a, s) => Array.from(crypto.createHash("sha256").update(s).digest()).map((b) => (b > 127 ? b - 256 : b)), getUuid: () => crypto.randomUUID() },
  PropertiesService: { getScriptProperties: () => ({ getProperty: (k) => props[k] || null, deleteProperty: (k) => { delete props[k]; } }) }, ContentService: { MimeType: { JSON: "json" }, createTextOutput: (s) => ({ s, setMimeType() { return this; } }) }, Logger: { log() {} }, Session: { getEffectiveUser: () => ({ getEmail: () => "owner@example.com" }) }, console };
vm.createContext(sb); vm.runInContext(fs.readFileSync(codePath || path.join(root, "dist/Code_Ledger.gs"), "utf8") + (extraSource || "") + "\nthis.doPost=doPost;this.initAdmin=initAdmin;this.setupAdmin=setupAdmin;this.dailyBackup=dailyBackup;this.restoreFromProperty=restoreFromProperty;this.installSOBRecords=typeof installSOBRecords===\"function\"?installSOBRecords:null;", sb);
  const call = async (b) => JSON.parse(sb.doPost({ postData: { contents: JSON.stringify(b) } }).s);
  const session = (token) => (b) => call(Object.assign({ token }, b));
  return { sb, props, sheets, call, session, setupAdmin: () => sb.setupAdmin() };
}
module.exports = { start };
